package blockchain

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/conseweb/common/fabricGoSDK/models"
)

// GetChainReader is a Reader for the GetChain structure.
type GetChainReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetChainReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetChainOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetChainDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetChainOK creates a GetChainOK with default headers values
func NewGetChainOK() *GetChainOK {
	return &GetChainOK{}
}

/*GetChainOK handles this case with default header values.

Blockchain information
*/
type GetChainOK struct {
	Payload *models.BlockchainInfo
}

func (o *GetChainOK) Error() string {
	return fmt.Sprintf("[GET /chain][%d] getChainOK  %+v", 200, o.Payload)
}

func (o *GetChainOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BlockchainInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetChainDefault creates a GetChainDefault with default headers values
func NewGetChainDefault(code int) *GetChainDefault {
	return &GetChainDefault{
		_statusCode: code,
	}
}

/*GetChainDefault handles this case with default header values.

Unexpected error
*/
type GetChainDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get chain default response
func (o *GetChainDefault) Code() int {
	return o._statusCode
}

func (o *GetChainDefault) Error() string {
	return fmt.Sprintf("[GET /chain][%d] getChain default  %+v", o._statusCode, o.Payload)
}

func (o *GetChainDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
