package blockchain

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetChainParams creates a new GetChainParams object
// with the default values initialized.
func NewGetChainParams() *GetChainParams {

	return &GetChainParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetChainParamsWithTimeout creates a new GetChainParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetChainParamsWithTimeout(timeout time.Duration) *GetChainParams {

	return &GetChainParams{

		timeout: timeout,
	}
}

/*GetChainParams contains all the parameters to send to the API endpoint
for the get chain operation typically these are written to a http.Request
*/
type GetChainParams struct {
	timeout time.Duration
}

// WriteToRequest writes these params to a swagger request
func (o *GetChainParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
