package registrar

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/conseweb/common/fabricGoSDK/models"
)

// DeleteUserRegistrationReader is a Reader for the DeleteUserRegistration structure.
type DeleteUserRegistrationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteUserRegistrationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteUserRegistrationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteUserRegistrationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewDeleteUserRegistrationOK creates a DeleteUserRegistrationOK with default headers values
func NewDeleteUserRegistrationOK() *DeleteUserRegistrationOK {
	return &DeleteUserRegistrationOK{}
}

/*DeleteUserRegistrationOK handles this case with default header values.

Confirm deletion of user login tokens
*/
type DeleteUserRegistrationOK struct {
	Payload *models.OK
}

func (o *DeleteUserRegistrationOK) Error() string {
	return fmt.Sprintf("[DELETE /registrar/{enrollmentID}][%d] deleteUserRegistrationOK  %+v", 200, o.Payload)
}

func (o *DeleteUserRegistrationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OK)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteUserRegistrationDefault creates a DeleteUserRegistrationDefault with default headers values
func NewDeleteUserRegistrationDefault(code int) *DeleteUserRegistrationDefault {
	return &DeleteUserRegistrationDefault{
		_statusCode: code,
	}
}

/*DeleteUserRegistrationDefault handles this case with default header values.

Unexpected error
*/
type DeleteUserRegistrationDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete user registration default response
func (o *DeleteUserRegistrationDefault) Code() int {
	return o._statusCode
}

func (o *DeleteUserRegistrationDefault) Error() string {
	return fmt.Sprintf("[DELETE /registrar/{enrollmentID}][%d] deleteUserRegistration default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteUserRegistrationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
