package registrar

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteUserRegistrationParams creates a new DeleteUserRegistrationParams object
// with the default values initialized.
func NewDeleteUserRegistrationParams() *DeleteUserRegistrationParams {
	var ()
	return &DeleteUserRegistrationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteUserRegistrationParamsWithTimeout creates a new DeleteUserRegistrationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteUserRegistrationParamsWithTimeout(timeout time.Duration) *DeleteUserRegistrationParams {
	var ()
	return &DeleteUserRegistrationParams{

		timeout: timeout,
	}
}

/*DeleteUserRegistrationParams contains all the parameters to send to the API endpoint
for the delete user registration operation typically these are written to a http.Request
*/
type DeleteUserRegistrationParams struct {

	/*EnrollmentID
	  Username for which login tokens are to be deleted

	*/
	EnrollmentID string

	timeout time.Duration
}

// WithEnrollmentID adds the enrollmentID to the delete user registration params
func (o *DeleteUserRegistrationParams) WithEnrollmentID(enrollmentID string) *DeleteUserRegistrationParams {
	o.EnrollmentID = enrollmentID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteUserRegistrationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param enrollmentID
	if err := r.SetPathParam("enrollmentID", o.EnrollmentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
