package registrar

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/conseweb/common/fabricGoSDK/models"
)

// GetUserTransactionCertificateReader is a Reader for the GetUserTransactionCertificate structure.
type GetUserTransactionCertificateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetUserTransactionCertificateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetUserTransactionCertificateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetUserTransactionCertificateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetUserTransactionCertificateOK creates a GetUserTransactionCertificateOK with default headers values
func NewGetUserTransactionCertificateOK() *GetUserTransactionCertificateOK {
	return &GetUserTransactionCertificateOK{}
}

/*GetUserTransactionCertificateOK handles this case with default header values.

Confirm registration for target user and return the desired number of URL-encoded transaction certificates
*/
type GetUserTransactionCertificateOK struct {
	Payload *models.OK
}

func (o *GetUserTransactionCertificateOK) Error() string {
	return fmt.Sprintf("[GET /registrar/{enrollmentID}/tcert][%d] getUserTransactionCertificateOK  %+v", 200, o.Payload)
}

func (o *GetUserTransactionCertificateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OK)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUserTransactionCertificateDefault creates a GetUserTransactionCertificateDefault with default headers values
func NewGetUserTransactionCertificateDefault(code int) *GetUserTransactionCertificateDefault {
	return &GetUserTransactionCertificateDefault{
		_statusCode: code,
	}
}

/*GetUserTransactionCertificateDefault handles this case with default header values.

Unexpected error
*/
type GetUserTransactionCertificateDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get user transaction certificate default response
func (o *GetUserTransactionCertificateDefault) Code() int {
	return o._statusCode
}

func (o *GetUserTransactionCertificateDefault) Error() string {
	return fmt.Sprintf("[GET /registrar/{enrollmentID}/tcert][%d] getUserTransactionCertificate default  %+v", o._statusCode, o.Payload)
}

func (o *GetUserTransactionCertificateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
