package registrar

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetUserEnrollmentCertificateParams creates a new GetUserEnrollmentCertificateParams object
// with the default values initialized.
func NewGetUserEnrollmentCertificateParams() *GetUserEnrollmentCertificateParams {
	var ()
	return &GetUserEnrollmentCertificateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserEnrollmentCertificateParamsWithTimeout creates a new GetUserEnrollmentCertificateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUserEnrollmentCertificateParamsWithTimeout(timeout time.Duration) *GetUserEnrollmentCertificateParams {
	var ()
	return &GetUserEnrollmentCertificateParams{

		timeout: timeout,
	}
}

/*GetUserEnrollmentCertificateParams contains all the parameters to send to the API endpoint
for the get user enrollment certificate operation typically these are written to a http.Request
*/
type GetUserEnrollmentCertificateParams struct {

	/*EnrollmentID
	  EnrollmentID for which the certificate is requested

	*/
	EnrollmentID string

	timeout time.Duration
}

// WithEnrollmentID adds the enrollmentID to the get user enrollment certificate params
func (o *GetUserEnrollmentCertificateParams) WithEnrollmentID(enrollmentID string) *GetUserEnrollmentCertificateParams {
	o.EnrollmentID = enrollmentID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserEnrollmentCertificateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param enrollmentID
	if err := r.SetPathParam("enrollmentID", o.EnrollmentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
