package registrar

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetUserRegistrationParams creates a new GetUserRegistrationParams object
// with the default values initialized.
func NewGetUserRegistrationParams() *GetUserRegistrationParams {
	var ()
	return &GetUserRegistrationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserRegistrationParamsWithTimeout creates a new GetUserRegistrationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUserRegistrationParamsWithTimeout(timeout time.Duration) *GetUserRegistrationParams {
	var ()
	return &GetUserRegistrationParams{

		timeout: timeout,
	}
}

/*GetUserRegistrationParams contains all the parameters to send to the API endpoint
for the get user registration operation typically these are written to a http.Request
*/
type GetUserRegistrationParams struct {

	/*EnrollmentID
	  Username for which registration is to be confirmed

	*/
	EnrollmentID string

	timeout time.Duration
}

// WithEnrollmentID adds the enrollmentID to the get user registration params
func (o *GetUserRegistrationParams) WithEnrollmentID(enrollmentID string) *GetUserRegistrationParams {
	o.EnrollmentID = enrollmentID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserRegistrationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param enrollmentID
	if err := r.SetPathParam("enrollmentID", o.EnrollmentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
