package registrar

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/conseweb/common/fabricGoSDK/models"
)

// RegisterUserReader is a Reader for the RegisterUser structure.
type RegisterUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *RegisterUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRegisterUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewRegisterUserDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewRegisterUserOK creates a RegisterUserOK with default headers values
func NewRegisterUserOK() *RegisterUserOK {
	return &RegisterUserOK{}
}

/*RegisterUserOK handles this case with default header values.

Successfully registered user with the certificate authority
*/
type RegisterUserOK struct {
	Payload *models.OK
}

func (o *RegisterUserOK) Error() string {
	return fmt.Sprintf("[POST /registrar][%d] registerUserOK  %+v", 200, o.Payload)
}

func (o *RegisterUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OK)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRegisterUserDefault creates a RegisterUserDefault with default headers values
func NewRegisterUserDefault(code int) *RegisterUserDefault {
	return &RegisterUserDefault{
		_statusCode: code,
	}
}

/*RegisterUserDefault handles this case with default header values.

Unexpected error
*/
type RegisterUserDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the register user default response
func (o *RegisterUserDefault) Code() int {
	return o._statusCode
}

func (o *RegisterUserDefault) Error() string {
	return fmt.Sprintf("[POST /registrar][%d] registerUser default  %+v", o._statusCode, o.Payload)
}

func (o *RegisterUserDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
