package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*BlockchainInfo blockchain info

swagger:model BlockchainInfo
*/
type BlockchainInfo struct {

	/* Hash of the last block in the blockchain.
	 */
	CurrentBlockHash string `json:"currentBlockHash,omitempty"`

	/* Current height of the blockchain.
	 */
	Height uint64 `json:"height,omitempty"`

	/* Hash of the previous block in the blockchain.
	 */
	PreviousBlockHash string `json:"previousBlockHash,omitempty"`
}

// Validate validates this blockchain info
func (m *BlockchainInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
