package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

/*ChaincodeInvocationSpec chaincode invocation spec

swagger:model ChaincodeInvocationSpec
*/
type ChaincodeInvocationSpec struct {

	/* Chaincode specification message.
	 */
	ChaincodeSpec *ChaincodeSpec `json:"chaincodeSpec,omitempty"`
}

// Validate validates this chaincode invocation spec
func (m *ChaincodeInvocationSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChaincodeSpec(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChaincodeInvocationSpec) validateChaincodeSpec(formats strfmt.Registry) error {

	if swag.IsZero(m.ChaincodeSpec) { // not required
		return nil
	}

	if m.ChaincodeSpec != nil {

		if err := m.ChaincodeSpec.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
