package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

/*ChaincodeInput chaincode input

swagger:model ChaincodeInput
*/
type ChaincodeInput struct {

	/* Arguments supplied to the Chaincode function.
	 */
	Args []string `json:"args,omitempty"`
}

// Validate validates this chaincode input
func (m *ChaincodeInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateArgs(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChaincodeInput) validateArgs(formats strfmt.Registry) error {

	if swag.IsZero(m.Args) { // not required
		return nil
	}

	return nil
}
