package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*ChaincodeID chaincode ID

swagger:model ChaincodeID
*/
type ChaincodeID struct {

	/* Chaincode name identifier. This value is required by the invoke and query transactions.
	 */
	Name string `json:"name,omitempty"`

	/* Chaincode location in the file system. This value is required by the deploy transaction.
	 */
	Path string `json:"path,omitempty"`
}

// Validate validates this chaincode ID
func (m *ChaincodeID) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
