package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*OK o k

swagger:model OK
*/
type OK struct {

	/* A descriptive message confirming a successful request.
	 */
	OK string `json:"OK,omitempty"`

	/* An optional parameter containing additional information about the request.
	 */
	Message string `json:"message,omitempty"`
}

// Validate validates this o k
func (m *OK) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
