package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

/*PeersMessage peers message

swagger:model PeersMessage
*/
type PeersMessage struct {

	/* peers
	 */
	Peers []*PeerEndpoint `json:"peers,omitempty"`
}

// Validate validates this peers message
func (m *PeersMessage) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePeers(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PeersMessage) validatePeers(formats strfmt.Registry) error {

	if swag.IsZero(m.Peers) { // not required
		return nil
	}

	for i := 0; i < len(m.Peers); i++ {

		if swag.IsZero(m.Peers[i]) { // not required
			continue
		}

		if m.Peers[i] != nil {

			if err := m.Peers[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}
