package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*RPCResponse rpc response

swagger:model rpcResponse
*/
type RPCResponse struct {

	/* Additional information about the response or values returned.
	 */
	Message *string `json:"Message,omitempty"`

	/* A string confirming successful request execution.

	Required: true
	*/
	Status *string `json:"Status"`
}

// Validate validates this rpc response
func (m *RPCResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RPCResponse) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("Status", "body", m.Status); err != nil {
		return err
	}

	return nil
}
