package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*Secret secret

swagger:model Secret
*/
type Secret struct {

	/* User enrollment id registered with the certificate authority.
	 */
	EnrollID string `json:"enrollId,omitempty"`

	/* User enrollment password registered with the certificate authority.
	 */
	EnrollSecret string `json:"enrollSecret,omitempty"`
}

// Validate validates this secret
func (m *Secret) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
