package block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new block API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for block API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetBlock individuals block information

The {Block} endpoint returns information about a specific block within the Blockchain. Note that the genesis block is block zero.
*/
func (a *Client) GetBlock(params *GetBlockParams) (*GetBlockOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetBlockParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getBlock",
		Method:             "GET",
		PathPattern:        "/chain/blocks/{Block}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetBlockReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetBlockOK), nil
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
