package block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBlockParams creates a new GetBlockParams object
// with the default values initialized.
func NewGetBlockParams() *GetBlockParams {
	var ()
	return &GetBlockParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBlockParamsWithTimeout creates a new GetBlockParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBlockParamsWithTimeout(timeout time.Duration) *GetBlockParams {
	var ()
	return &GetBlockParams{

		timeout: timeout,
	}
}

/*GetBlockParams contains all the parameters to send to the API endpoint
for the get block operation typically these are written to a http.Request
*/
type GetBlockParams struct {

	/*Block
	  Block number to retrieve

	*/
	Block uint64

	timeout time.Duration
}

// WithBlock adds the block to the get block params
func (o *GetBlockParams) WithBlock(block uint64) *GetBlockParams {
	o.Block = block
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetBlockParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param Block
	if err := r.SetPathParam("Block", swag.FormatUint64(o.Block)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
