package network

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/conseweb/common/fabricGoSDK/models"
)

// GetPeersReader is a Reader for the GetPeers structure.
type GetPeersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetPeersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPeersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetPeersDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetPeersOK creates a GetPeersOK with default headers values
func NewGetPeersOK() *GetPeersOK {
	return &GetPeersOK{}
}

/*GetPeersOK handles this case with default header values.

List of network peers
*/
type GetPeersOK struct {
	Payload *models.PeersMessage
}

func (o *GetPeersOK) Error() string {
	return fmt.Sprintf("[GET /network/peers][%d] getPeersOK  %+v", 200, o.Payload)
}

func (o *GetPeersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PeersMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPeersDefault creates a GetPeersDefault with default headers values
func NewGetPeersDefault(code int) *GetPeersDefault {
	return &GetPeersDefault{
		_statusCode: code,
	}
}

/*GetPeersDefault handles this case with default header values.

Unexpected error
*/
type GetPeersDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get peers default response
func (o *GetPeersDefault) Code() int {
	return o._statusCode
}

func (o *GetPeersDefault) Error() string {
	return fmt.Sprintf("[GET /network/peers][%d] getPeers default  %+v", o._statusCode, o.Payload)
}

func (o *GetPeersDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
