package network

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPeersParams creates a new GetPeersParams object
// with the default values initialized.
func NewGetPeersParams() *GetPeersParams {

	return &GetPeersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPeersParamsWithTimeout creates a new GetPeersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPeersParamsWithTimeout(timeout time.Duration) *GetPeersParams {

	return &GetPeersParams{

		timeout: timeout,
	}
}

/*GetPeersParams contains all the parameters to send to the API endpoint
for the get peers operation typically these are written to a http.Request
*/
type GetPeersParams struct {
	timeout time.Duration
}

// WriteToRequest writes these params to a swagger request
func (o *GetPeersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
