package network

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new network API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for network API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetPeers lists of network peers

The /network/peers endpoint returns a list of all existing network connections for the target peer node. The list includes both validating and non-validating peers.
*/
func (a *Client) GetPeers(params *GetPeersParams) (*GetPeersOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetPeersParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getPeers",
		Method:             "GET",
		PathPattern:        "/network/peers",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetPeersReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetPeersOK), nil
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
