// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	StoreEntity
	QueryEntity
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 存储实体
type StoreEntity struct {
	// 键
	Key string `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
	// 长度
	Length int64 `protobuf:"varint,2,opt,name=Length" json:"Length,omitempty"`
	// 值
	Value []byte `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (m *StoreEntity) Reset()                    { *m = StoreEntity{} }
func (m *StoreEntity) String() string            { return proto.CompactTextString(m) }
func (*StoreEntity) ProtoMessage()               {}
func (*StoreEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 查询实体
type QueryEntity struct {
	// 键
	Key string `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
	// 是否存在
	IsExist bool `protobuf:"varint,2,opt,name=IsExist" json:"IsExist,omitempty"`
}

func (m *QueryEntity) Reset()                    { *m = QueryEntity{} }
func (m *QueryEntity) String() string            { return proto.CompactTextString(m) }
func (*QueryEntity) ProtoMessage()               {}
func (*QueryEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*StoreEntity)(nil), "main.StoreEntity")
	proto.RegisterType((*QueryEntity)(nil), "main.QueryEntity")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53,
	0xf2, 0xe5, 0xe2, 0x0e, 0x2e, 0xc9, 0x2f, 0x4a, 0x75, 0xcd, 0x2b, 0xc9, 0x2c, 0xa9, 0x14, 0x12,
	0xe0, 0x62, 0xf6, 0x4e, 0xad, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x85, 0xc4,
	0xb8, 0xd8, 0x7c, 0x52, 0xf3, 0xd2, 0x4b, 0x32, 0x24, 0x98, 0x14, 0x18, 0x35, 0x98, 0x83, 0xa0,
	0x3c, 0x21, 0x11, 0x2e, 0xd6, 0xb0, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x9e,
	0x20, 0x08, 0x47, 0xc9, 0x92, 0x8b, 0x3b, 0xb0, 0x34, 0xb5, 0xa8, 0x12, 0xa7, 0x71, 0x12, 0x5c,
	0xec, 0x9e, 0xc5, 0xae, 0x15, 0x99, 0xc5, 0x25, 0x60, 0xf3, 0x38, 0x82, 0x60, 0xdc, 0x24, 0x36,
	0xb0, 0xb3, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x61, 0xf6, 0x03, 0x6c, 0xa7, 0x00, 0x00,
	0x00,
}
