package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/conseweb/common/fabricGoSDK/models"
)

// GetTransactionReader is a Reader for the GetTransaction structure.
type GetTransactionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetTransactionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTransactionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetTransactionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetTransactionOK creates a GetTransactionOK with default headers values
func NewGetTransactionOK() *GetTransactionOK {
	return &GetTransactionOK{}
}

/*GetTransactionOK handles this case with default header values.

Individual Transaction contents
*/
type GetTransactionOK struct {
	Payload *models.Transaction
}

func (o *GetTransactionOK) Error() string {
	return fmt.Sprintf("[GET /transactions/{ID}][%d] getTransactionOK  %+v", 200, o.Payload)
}

func (o *GetTransactionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Transaction)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTransactionDefault creates a GetTransactionDefault with default headers values
func NewGetTransactionDefault(code int) *GetTransactionDefault {
	return &GetTransactionDefault{
		_statusCode: code,
	}
}

/*GetTransactionDefault handles this case with default header values.

Unexpected error
*/
type GetTransactionDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get transaction default response
func (o *GetTransactionDefault) Code() int {
	return o._statusCode
}

func (o *GetTransactionDefault) Error() string {
	return fmt.Sprintf("[GET /transactions/{ID}][%d] getTransaction default  %+v", o._statusCode, o.Payload)
}

func (o *GetTransactionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
