package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new transactions API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for transactions API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetTransaction individuals transaction contents

The /transactions/{ID} endpoint returns the transaction matching the specified TXID.
*/
func (a *Client) GetTransaction(params *GetTransactionParams) (*GetTransactionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetTransactionParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getTransaction",
		Method:             "GET",
		PathPattern:        "/transactions/{ID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetTransactionReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetTransactionOK), nil
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
