package chaincode

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/conseweb/common/fabricGoSDK/models"
)

// ChaincodeInvokeReader is a Reader for the ChaincodeInvoke structure.
type ChaincodeInvokeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *ChaincodeInvokeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewChaincodeInvokeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewChaincodeInvokeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewChaincodeInvokeOK creates a ChaincodeInvokeOK with default headers values
func NewChaincodeInvokeOK() *ChaincodeInvokeOK {
	return &ChaincodeInvokeOK{}
}

/*ChaincodeInvokeOK handles this case with default header values.

Successfully invoked transaction
*/
type ChaincodeInvokeOK struct {
	Payload *models.OK
}

func (o *ChaincodeInvokeOK) Error() string {
	return fmt.Sprintf("[POST /devops/invoke][%d] chaincodeInvokeOK  %+v", 200, o.Payload)
}

func (o *ChaincodeInvokeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OK)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewChaincodeInvokeDefault creates a ChaincodeInvokeDefault with default headers values
func NewChaincodeInvokeDefault(code int) *ChaincodeInvokeDefault {
	return &ChaincodeInvokeDefault{
		_statusCode: code,
	}
}

/*ChaincodeInvokeDefault handles this case with default header values.

Unexpected error
*/
type ChaincodeInvokeDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the chaincode invoke default response
func (o *ChaincodeInvokeDefault) Code() int {
	return o._statusCode
}

func (o *ChaincodeInvokeDefault) Error() string {
	return fmt.Sprintf("[POST /devops/invoke][%d] chaincodeInvoke default  %+v", o._statusCode, o.Payload)
}

func (o *ChaincodeInvokeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
