package chaincode

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/conseweb/common/fabricGoSDK/models"
)

// NewChaincodeInvokeParams creates a new ChaincodeInvokeParams object
// with the default values initialized.
func NewChaincodeInvokeParams() *ChaincodeInvokeParams {
	var ()
	return &ChaincodeInvokeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewChaincodeInvokeParamsWithTimeout creates a new ChaincodeInvokeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewChaincodeInvokeParamsWithTimeout(timeout time.Duration) *ChaincodeInvokeParams {
	var ()
	return &ChaincodeInvokeParams{

		timeout: timeout,
	}
}

/*ChaincodeInvokeParams contains all the parameters to send to the API endpoint
for the chaincode invoke operation typically these are written to a http.Request
*/
type ChaincodeInvokeParams struct {

	/*ChaincodeInvocationSpec
	  Chaincode invocation message

	*/
	ChaincodeInvocationSpec *models.ChaincodeInvocationSpec

	timeout time.Duration
}

// WithChaincodeInvocationSpec adds the chaincodeInvocationSpec to the chaincode invoke params
func (o *ChaincodeInvokeParams) WithChaincodeInvocationSpec(chaincodeInvocationSpec *models.ChaincodeInvocationSpec) *ChaincodeInvokeParams {
	o.ChaincodeInvocationSpec = chaincodeInvocationSpec
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ChaincodeInvokeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.ChaincodeInvocationSpec == nil {
		o.ChaincodeInvocationSpec = new(models.ChaincodeInvocationSpec)
	}

	if err := r.SetBodyParam(o.ChaincodeInvocationSpec); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
